### PR TITLE
Cache throwable in ExceptionMatcher to avoid executing procedure twice

### LINKED ISSUE #58: The procedure call from exception matcher is called twice when a mismatch is found
**Describe the bug**
The ExceptionMatcher calls the procedure/lambda under test twice when a mismatch is found.
The first call is used to catch the exception, and a second call appears to happen during mismatch description.
This is problematic when the code under test has side effects (e.g., EasyMock mocks that are configured to return a value only once, or that change state after the first call).
On the second invocation, the mock may return a different result, meaning the exception is no longer thrown, which causes a confusing or incorrect test failure.

**Describe your setup (please complete the following information):**
- junit-utils version: 1.9.0
- JUnit version: JUnit 4
- Java provider and version: Red Hat OpenJDK 17.0.9+9-LTS
- OS and version: Windows 11

**Steps to Reproduce**

1. Set up an EasyMock mock that returns a specific value once (using .times(1) or default behavior), causing the code under test to throw an exception on that call.
2. Use assertThat(() -> myService.doSomething(), throwsException(SomeException.class).withMessage("expected")) where the message doesn't match (to trigger a mismatch).
3. The matcher calls the lambda a first time — exception is thrown and caught correctly.
4. The matcher calls the lambda a second time during mismatch reporting — but now the mock returns a different value (or default/null), so the exception is not thrown.
5. The test fails with a misleading error, or the mismatch description is wrong.

Minimal reproducer:

```java
@Test
public void testDoubleInvocation()                                                                                                                                                                                                                                                                                    
{                                                                                                                                                                                                                                                                                                                     
    MyService service = createMock(MyService.class);                                                                                                                                                                                                                                                                  
    expect(service.process()).andThrow(new ComponentException("ERROR_CODE")).once();                                                                                                                                                                                                                                  
    expect(service.process()).andReturn(null); // second call won't throw                                                                                                                                                                                                                                             
    replay(service);                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                      
    // This will call service.process() TWICE if the message matcher doesn't match                                                                                                                                                                                                                                    
    assertThat(() -> service.process(),                                                                                                                                                                                                                                                                               
        throwsException(ComponentException.class)                                                                                                                                                                                                                                                                     
            .withMessage("WRONG_MESSAGE")); // intentional mismatch to demonstrate the bug                                                                                                                                                                                                                            
}                                                                                                                                                                                                                                                                                                                     
```        

**Expected behavior**
The ExceptionMatcher should call the lambda/procedure exactly once, cache the result (the thrown exception), and use the cached exception for both matching and mismatch description. The procedure under test should never be invoked a second time.

**Logs/Screenshots**

With sensitive data omitted

```
java.lang.AssertionError: 
Expected: 
          ValidationException
          with message: "XXXX"
     but: 
          no exception was thrown
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at MyClass.mytest(MyTest.java:215)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

**Additional context**
This is particularly impactful with mock frameworks like EasyMock where mock expectations are consumed on each call. After the first invocation consumes the expectation, the second invocation either returns a default value, throws an unexpected-call error, or behaves differently — all of which mask the real 
test result.

### PR DESCRIPTION
**Pull request by lellisls**
Fixes #58

### CODE REVIEW

File: src/test/java/net/obvj/junit/utils/matchers/ExceptionMatcherTest.java [hunk 1]
```diff
@@ -887,4 +888,30 @@ void with_mixedMessageContainingAndValidFunctionsAndOneMatcherNotMatching_except
...
+
+    @Test
+    void with_methodThatChangeStateOnSecondCall()
+    {
+        MockedMethod mockedMethod = new MockedMethod();
+        try
+        {
+            assertThat(mockedMethod::method, throwsException(RuntimeException.class).withMessage("OtherMessage"));
+            fail("Expected AssertionError");
+        } catch (AssertionError error)
```
Comment (oswaldobapvicjr) [inline src/test/java/net/obvj/junit/utils/matchers/ExceptionMatcherTest.java]: Add a new line before `catch`

File: src/main/java/net/obvj/junit/utils/matchers/ExceptionMatcher.java [hunk 2]
```diff
@@ -777,12 +777,18 @@ protected boolean matchesSafely(Procedure procedure, Description mismatch)
     {
         try
         {
+            // This function may be called twice. Then the exception is saved in the matcher
+            if(cachedThrowable != null)
```
Comment (oswaldobapvicjr) [inline src/main/java/net/obvj/junit/utils/matchers/ExceptionMatcher.java]: Add a space between `if` and `(`

**Review by oswaldobapvicjr — COMMENTED** [review]
Thank you @lellisls for the issue and the Pull Request. Just please address these two small comments about formatting before we can merge it.

**Review by oswaldobapvicjr — APPROVED** [review]
